"""add_document_progress_fields

Revision ID: 86c052853518
Revises: 999af97b7855
Create Date: 2026-04-07 19:25:47.474863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c052853518'
down_revision: Union[str, None] = '999af97b7855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_step', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('progress_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'progress_percent')
    op.drop_column('documents', 'processing_step')
    # ### end Alembic commands ###
